package com.fiap.pos.tech.challenge.enums;

public enum StatusEnum {
    COTACAO_SOLICITADA,
    COTACAO_ENVIADA,
    COTACAO_APROVADA,
    COTACAO_RECUSADA,
    APOLICE_SOLICITADA,
    APOLICE_EMITIDA,
    APOLICE_ENCERRADA,
    APOLICE_CANCELADA
}
