version: '3.7'
services:
  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=NOT_VALID_KEY
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_SECRET_ACCESS_KEY=NOT_VALID_SECRET
    ports:
      - '4566:4566'