version: '3.7'
services:
  aws:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=NOT_VALID_KEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=NOT_VALID_SECRET
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway